### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by vincentsarago** [developmentseed/timvt#3]
Right now the tiler is working and the structure is in 👌 shape. 

Here is the list of what needs to be done:
- [ ] add Tests for the /tiles endpoint
- [ ] add conformance endpoint?
- [ ] add projections demos

I've added timings in the responses headers to monitor the performances.

cc @bitner
